# p1/Vagrantfile
Vagrant.configure("2") do |config|
    # Use Ubuntu 20.04 LTS (Focal)
    config.vm.box = "ubuntu/focal64"
    config.vm.box_version = "20240221.0.0"
  
    # Server Node
    config.vm.define "hboumahdS" do |server|
      server.vm.hostname = "hboumahdS"
      server.vm.network "private_network", ip: "192.168.56.110"
      
      server.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
        vb.name = "hboumahdS"
      end
  
      server.vm.provision "shell", path: "scripts/k3s-server-install.sh"
    end
  
    # Worker Node
    config.vm.define "hboumahdSW" do |worker|
      worker.vm.hostname = "hboumahdSW"
      worker.vm.network "private_network", ip: "192.168.56.111"
      
      worker.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
        vb.name = "hboumahdSW"
      end
  
      worker.vm.provision "shell", path: "scripts/k3s-agent-install.sh"
    end
  end